export enum EPuzzleSymbols {
    NOT = "!",
    NOT_EQUAL = "≠",
    EQUAL = "=",
    AND = "&",
    OR = "|",
    FALSE = "F",
    TRUE = "T",
    LESS_THAN = "<",
    LESS_THAN_OR_EQUAL = "≤",
    GREATER_THAN_OR_EQUAL = "≥",
    GREATER_THAN = ">",
    OPENING_PARENTHESIS = "(",
    CLOSING_PARENTHESIS = ")",
    ZERO = "0",
    ONE = "1",
    TWO = "2",
    THREE = "3",
    FOUR = "4",
    FIVE = "5",
    SIX = "6",
    SEVEN = "7",
    EIGHT = "8",
    NINE = "9",
}

export const puzzleSymbolMap : { [ K in EPuzzleSymbols ]: string } = {
    [ EPuzzleSymbols.NOT ]: "!",
    [ EPuzzleSymbols.NOT_EQUAL ]: "!=",
    [ EPuzzleSymbols.EQUAL ]: "==",
    [ EPuzzleSymbols.AND ]: "&&",
    [ EPuzzleSymbols.OR ]: "||",
    [ EPuzzleSymbols.FALSE ]: "F",
    [ EPuzzleSymbols.TRUE ]: "T",
    [ EPuzzleSymbols.LESS_THAN ]: "<",
    [ EPuzzleSymbols.LESS_THAN_OR_EQUAL ]: "<=",
    [ EPuzzleSymbols.GREATER_THAN_OR_EQUAL ]: ">=",
    [ EPuzzleSymbols.GREATER_THAN ]: ">",
    [ EPuzzleSymbols.OPENING_PARENTHESIS ]: "(",
    [ EPuzzleSymbols.CLOSING_PARENTHESIS ]: ")",
    [ EPuzzleSymbols.ZERO ]: "0",
    [ EPuzzleSymbols.ONE ]: "1",
    [ EPuzzleSymbols.TWO ]: "2",
    [ EPuzzleSymbols.THREE ]: "3",
    [ EPuzzleSymbols.FOUR ]: "4",
    [ EPuzzleSymbols.FIVE ]: "5",
    [ EPuzzleSymbols.SIX ]: "6",
    [ EPuzzleSymbols.SEVEN ]: "7",
    [ EPuzzleSymbols.EIGHT ]: "8",
    [ EPuzzleSymbols.NINE ]: "9",
}